version: '3.7'
services:
  database:
    container_name: postgres-telergam
    image: postgres
    environment:
      POSTGRES_DB: "pressure_diary"
      POSTGRES_USER: "telegramuser"
      POSTGRES_PASSWORD: "telegramuser"
    ports:
      - "5432:5432"
    volumes:
      - postgres-local-volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-local-volume:
    driver: local
